### ISSUE TITLE
Metabase Terraform Provider error

### ISSUE THREAD

**Issue by williamsbdev** [pulumi/pulumi-terraform-provider#34]
### What happened?

When I tried to do a simple Pulumi Project with the [Metabase Terraform provider](https://registry.terraform.io/providers/flovouin/metabase/latest), it panic'd and threw an error.

### Example

Example Project (config file also has the endpoint with `metabase:endpoint`):
```
import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';
import * as metabase from 'metabase';

const stackName = pulumi.getStack();

interface MetabaseResourcesArgs {
  name: string;
  subdomain: string;
  domainPrefix: string;
  domain: string;
}

async function createMetabaseResources(args: MetabaseResourcesArgs) {
  const {
    name,
    subdomain,
    domainPrefix,
    domain
  } = args;

  const metabaseApiKey = await aws.ssm.getParameter({
    name: `/${stackName}/${name}/api-key`,
    withDecryption: true,
  });

  const provider = new metabase.Provider(name, {
    endpoint: `https://${subdomain}${domainPrefix}.${domain}`,
    apiKey: metabaseApiKey.value,
  });

  new metabase.PermissionsGroup('brandon', {
    name: 'brandon',
  }, {
    provider,
  });
}

createMetabaseResources({name: 'metabase', subdomain: 'metabase', domainPrefix: '.staging', domain: 'foo.com'});
```

Output:
```
pulumi up --stack staging --diff
Previewing update (staging):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:staging::metabase::pulumi:pulumi:Stack::metabase-staging]
    + metabase:index/permissionsGroup:PermissionsGroup: (create)
        [urn=urn:pulumi:staging::metabase::metabase:index/permissionsGroup:PermissionsGroup::brandon]
        [provider=urn:pulumi:staging::metabase::pulumi:providers:metabase::metabase::47cc3a45-1010-49e0-9cfd-827263147717]
        name: "brandon"
Resources:
    + 1 to create
    1 unchanged
Do you want to perform this update? yes
Updating (staging):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:staging::metabase::pulumi:pulumi:Stack::metabase-staging]
    + metabase:index/permissionsGroup:PermissionsGroup: (create)
        [urn=urn:pulumi:staging::metabase::metabase:index/permissionsGroup:PermissionsGroup::brandon]
        [provider=urn:pulumi:staging::metabase::pulumi:providers:metabase::metabase::47cc3a45-1010-49e0-9cfd-827263147717]
        name: "brandon"
error: rpc error: code = Unavailable desc = error reading from server: EOF:

Stack trace from the terraform-provider-metabase_v0.8.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1006a3444]

goroutine 16 [running]:
github.com/flovouin/terraform-provider-metabase/internal/provider.(*PermissionsGroupResource).Create(0x140002e84e0, {0x100c2e5a8, 0x140002ed530}, {{{{0x100c333f8, 0x140002edb00}, {0x100b12fa0, 0x140002eda70}}, {0x100c356c8, 0x14000328280}}, {{{0x100c333f8, ...}, ...}, ...}, ...}, ...)
        github.com/flovouin/terraform-provider-metabase/internal/provider/permissions_group_resource.go:81 +0x1f4
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0x140001e01e0, {0x100c2e5a8, 0x140002ed530}, 0x140000495c8, 0x140000495a0)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_createresource.go:101 +0x400
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x140001e01e0, {0x100c2e5a8, 0x140002ed530}, 0x1400009b860, 0x140000496c0)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_applyresourcechange.go:57 +0x380
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0x140001e01e0, {0x100c2e5a8?, 0x140002ed440?}, 0x1400009b7c0)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/proto6server/server_applyresourcechange.go:55 +0x2e0
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x140001f0aa0, {0x100c2e5a8?, 0x140002ecab0?}, 0x140001e5c70)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x2a8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x100bfd280, 0x140001f0aa0}, {0x100c2e5a8, 0x140002ecab0}, 0x14000189780, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000184e00, {0x100c2e5a8, 0x140002eca20}, {0x100c34380, 0x14000476000}, 0x14000226fc0, 0x140002ec270, 0x10116a278, 0x0)
        google.golang.org/grpc@v1.66.0/server.go:1393 +0xb78
google.golang.org/grpc.(*Server).handleStream(0x14000184e00, {0x100c34380, 0x14000476000}, 0x14000226fc0)
        google.golang.org/grpc@v1.66.0/server.go:1804 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.0/server.go:1029 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 20
        google.golang.org/grpc@v1.66.0/server.go:1040 +0x13c

Error: The terraform-provider-metabase_v0.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

error: update failed
Resources:
    1 unchanged

Duration: 6s
```

### Output of `pulumi about`

```
pulumi about
CLI
Version      3.132.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME                VERSION
resource  aws                 6.50.1
resource  cloudflare          5.37.1
language  nodejs              3.132.0-dev.0
resource  terraform-provider  0.2.0
resource  terraform-provider  0.2.0

Host
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/brandonwilliams/.asdf/shims/node' version='v20.14.0'

Current Stack: organization/metabase/staging

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:staging::metabase::pulumi:pulumi:Stack::metabase-staging
pulumi:providers:metabase                          urn:pulumi:staging::metabase::pulumi:providers:metabase::metabase


Found no pending operations associated with staging

Backend
Name           williamsbdev.local
URL            s3://pulumi-state-123456789012/
User           brandonwilliams
Organizations
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/aws         6.50.1
@pulumi/cloudflare  5.37.1
@pulumi/pulumi      3.130.0
metabase            0.8.0
@types/node         18.19.45
typescript          5.5.4

Pulumi locates its logs in /var/folders/5g/cx7qqrgd601cmhcsxk7n0kdc0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @williamsbdev. Thanks for reporting an issue.

 I'll try to reproduce the panic tomorrow.

**Comment by iwahbe** [comment]
Hi @williamsbdev. Sorry for the delay. Unfortunately, this is a problem with the [upstream provider](https://registry.terraform.io/providers/flovouin/metabase/latest), not with pulumi-terraform-provider. I tried to consume the provider directly, and it panics in the same way.

<details>

<summary>HCL</summary>

```hcl
terraform {
  required_providers {
    metabase = {
      source = "flovouin/metabase"
    }
  }
}

provider "metabase" {
  endpoint = "http://127.0.0.1:3000"

  api_key = "mb_Q5D0iER0AXSS8Zdr0YsQ73+Dzr74uRlYB0nmB0tSfAw="
}

resource "metabase_permissions_group" "example" {
  name = "example"
}
```

</details>

<details>

<summary>Output</summary>

```console
$ terraform apply
tf apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # metabase_permissions_group.example will be created
  + resource "metabase_permissions_group" "example" {
      + id   = (known after apply)
      + name = "example"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

metabase_permissions_group.example: Creating...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-metabase_v0.8.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104b9b444]

goroutine 37 [running]:
github.com/flovouin/terraform-provider-metabase/internal/provider.(*PermissionsGroupResource).Create(0x14000412e70, {0x1051265a8, 0x14000512330}, {{{{0x10512b3f8, 0x14000512900}, {0x10500afa0, 0x14000512870}}, {0x10512d6c8, 0x1400042a960}}, {{{0x10512b3f8, ...}, ...}, ...}, ...}, ...)
        github.com/flovouin/terraform-provider-metabase/internal/provider/permissions_group_resource.go:81 +0x1f4
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0x140002821e0, {0x1051265a8, 0x14000512330}, 0x140000c35c8, 0x140000c35a0)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_createresource.go:101 +0x400
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x140002821e0, {0x1051265a8, 0x14000512330}, 0x1400042b2c0, 0x140000c36c0)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_applyresourcechange.go:57 +0x380
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0x140002821e0, {0x1051265a8?, 0x14000512240?}, 0x1400042b220)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/proto6server/server_applyresourcechange.go:55 +0x2e0
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x14000294aa0, {0x1051265a8?, 0x14000475830?}, 0x14000434f50)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x2a8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1050f5280, 0x14000294aa0}, {0x1051265a8, 0x14000475830}, 0x14000504380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000192e00, {0x1051265a8, 0x140004757a0}, {0x10512c380, 0x140000e6000}, 0x1400050a360, 0x1400038c270, 0x105662278, 0x0)
        google.golang.org/grpc@v1.66.0/server.go:1393 +0xb78
google.golang.org/grpc.(*Server).handleStream(0x14000192e00, {0x10512c380, 0x140000e6000}, 0x1400050a360)
        google.golang.org/grpc@v1.66.0/server.go:1804 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.0/server.go:1029 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 8
        google.golang.org/grpc@v1.66.0/server.go:1040 +0x13c

Error: The terraform-provider-metabase_v0.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

</details>

**Comment by iwahbe** [comment]
I opened https://github.com/flovouin/terraform-provider-metabase/issues/69 upstream.

**Comment by williamsbdev** [comment]
> Hi [@williamsbdev](https://github.com/williamsbdev). Sorry for the delay. Unfortunately, this is a problem with the [upstream provider](https://registry.terraform.io/providers/flovouin/metabase/latest), not with pulumi-terraform-provider. I tried to consume the provider directly, and it panics in the same way.
> 
> HCL
> Output

Gotcha! I should have thought to try this.

**Comment by williamsbdev** [comment]
> I opened [flovouin/terraform-provider-metabase#69](https://github.com/flovouin/terraform-provider-metabase/issues/69) upstream.

Thank you so much for the help with this! I appreciate you going the extra mile.
